ptm/tm/tm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView, RedirectView

import tmapp.controller

class TextPlainView(TemplateView):
    """
    See: http://www.netboy.pl/2011/10/add-favicon-ico-robots-txt-to-a-django-project/
    """
    def render_to_response(self, context, **kwargs):
        return super(TextPlainView, self).render_to_response(
            context, content_type='text/plain', **kwargs)

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/tm/'), name='site-root'),
    url(r'^tm/', include('tmapp.urls'), name='app-root'),
    url(r'^x', tmapp.controller.service_redirect),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^bye/$', 'django.contrib.auth.views.logout', {'next_page': '/tm'}),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^robots\.txt$', TextPlainView.as_view(template_name='robots.txt')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
)

ptm/tm/tmapp/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('tmapp.views',
    url(r'^$', 'index'),
    url(r'^playback/$', 'playback'),
    url(r'^playback/(?P<session_id>\d+)/$', 'playback'),
    url(r'^training/$', 'training'),
    url(r'^training/(?P<step_id>\d+)/$', 'training'),
    url(r'^training/ui/$', 'training_ui'),
    url(r'^translate/$', 'translate'),
    url(r'^demo/(?P<lang_pair>\w+)/$', 'demo'),
    url(r'^demographic/$', 'form_demographic'),
    url(r'^exit/$', 'form_exit'),
)

ptm/tm/tmapp/models.py
from django.db import models
from django.contrib.auth.models import User

import choices

## TODO:
##  * Add related_to field to ForeignKey objects? Did
##    that in the original impl and can't figure out why

class Language(models.Model):
    """ Specification of a (human) language. Mostly contains details for rendering the language in the browser.

    Has an autoincrementing id field.

    """
    # 2 character ISO-659-1 code (e.g., en)
    code = models.CharField(max_length=2,
                            choices=choices.LANGUAGES)

    layout_direction = models.CharField(max_length=3,
                                        choices=choices.LAYOUT)

    # This object will be used in forms, so just return the id
    def __unicode__(self):
        return dict(choices.LANGUAGES)[self.code]

class SourceDocument(models.Model):
    """
    A source document. 
    """
    url = models.CharField(max_length=150)
    domain = models.CharField(max_length=10)
    language = models.ForeignKey(Language,
                                 related_name='+')
    
    def __unicode__(self):
        return '%s %s %s' % (self.url, self.domain, self.language.code)
    
class UserConfiguration(models.Model):
    """
    Extends the User data model with application specific
    configuration settings.
    """
    user = models.OneToOneField(User)
    source_language = models.ForeignKey(Language,
                                        related_name='+')
    target_language = models.ForeignKey(Language,
                                        related_name='+')

    def __unicode__(self):
        return '%s %s->%s' % (self.user.username,
                              self.source_language.code,
                              self.target_language.code)

class Experiment(models.Model):
    """
    Created when a full experiment configuration is loaded.
    """
    name = models.CharField(max_length=100)
    json_spec = models.TextField()

    def __unicode__(self):
        return self.name
    
class TrainingRecord(models.Model):
    """
    Created when the user has completed training.
    
    """
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(auto_now=True,auto_now_add=True)

    def __unicode__(self):
        return self.user.username

class TranslationSession(models.Model):
    """
    A translation session bound to a unique
    user/document/interface tuple. Has an order field
    to indicate the order in which it should be presented
    to the user.
    """
    user = models.ForeignKey(User,related_name='+')
    src_document = models.ForeignKey(SourceDocument,
                                     related_name='+')
    tgt_language = models.ForeignKey(Language,
                                     related_name='+')

    interface = models.CharField(max_length=10, choices=choices.INTERFACES)
        
    # Order in which to present to the user
    order = models.PositiveIntegerField()

    create_time = models.DateTimeField(auto_now=True,
                                       auto_now_add=True,
                                       editable=False)

    start_time = models.DateTimeField(null=True,blank=True,editable=False)

    end_time = models.DateTimeField(null=True,blank=True,editable=False)
    
    complete = models.BooleanField(default=False,editable=False)

    training = models.BooleanField(default=False)

    valid = models.BooleanField(default=True)
    
    # Target text (separated by a delimiter)
    text = models.TextField(null=True,blank=True)
    
    # The session log
    log = models.TextField(null=True,blank=True)

    def __unicode__(self):
        return '%s %s ui: %s tgt_lang: %s done: %s training: %s order: %d' % (self.user.username,
                                                                    self.src_document.url,
                                                                    self.interface,
                                                                    self.tgt_language.code,
                                                                    str(self.complete),
                                                                    str(self.training),
                                                                              self.order)
    
class DemographicData(models.Model):
    """
    Demographic data about a user. Entered when the user consents to participate
    in the experiment.
    """
    user = models.OneToOneField(User)
    
    language_native = models.ForeignKey(Language,
                                        related_name='+')

    birth_country = models.CharField(max_length=2,
                                     choices=choices.COUNTRY_CHOICES)

    resident_of = models.CharField(max_length=2,
                                   choices=choices.COUNTRY_CHOICES)

    # Average number of hours that this user works as
    # a translator each week
    hours_per_week = models.PositiveIntegerField()

    is_pro_translator = models.BooleanField(choices=choices.BOOLEAN_CHOICES,
                                            default=False)

    src_proficiency = models.PositiveSmallIntegerField(choices=choices.ILR_CHOICES)

    tgt_proficiency = models.PositiveSmallIntegerField(choices=choices.ILR_CHOICES)

    cat_tool = models.CharField(max_length=20,
                                choices=choices.CAT_CHOICES,
                                default='none')

    cat_tool_opinion = models.PositiveSmallIntegerField(choices=choices.LIKERT_CHOICES,default=3)
    
    mt_opinion = models.PositiveSmallIntegerField(choices=choices.LIKERT_CHOICES,default=3)
    
    def __unicode__(self):
        return '%s: native:%s' % (self.user.username,
                                  self.language_native.code)

class ExitSurveyData(models.Model):
	"""
	Exit survey entered by the user after the experiment ends.
	"""
	user = models.OneToOneField(User)

        # Sanity check questions
        exit_data_comparison = models.BooleanField(choices=choices.BOOLEAN_CHOICES, default = None)
        exit_fatigue_comparison = models.BooleanField(choices=choices.BOOLEAN_CHOICES, default = None)
        exit_technical_comparison = models.TextField()

        # Linguistic difficulty questions
        exit_hardest_pos = models.CharField( max_length = 3, choices = choices.POS_CHOICES, default = None )
	exit_easiest_pos = models.CharField( max_length = 3, choices = choices.POS_CHOICES, default = None )
	exit_hardest_source = models.TextField()
	exit_hardest_target = models.TextField()

        # UI Comparison questions
        exit_focus_in_postedit = models.CharField( max_length = 5, choices = choices.POSTEDIT_GAZE, default = None )
	exit_focus_in_imt = models.CharField( max_length = 5, choices = choices.ITM_GAZE, default = None )
	exit_like_better = models.CharField( max_length = 3, choices = choices.INTERFACES, default = None )
	exit_more_efficient = models.CharField( max_length = 3, choices = choices.INTERFACES, default = None )

        # Interactive MT questions
	exit_itm_most_useful = models.CharField( max_length = 15, choices = choices.IMT_AID_CHOICES, default = None )
	exit_itm_least_useful = models.CharField( max_length = 15, choices = choices.IMT_AID_CHOICES, default = None )
	exit_useful_src_lookup = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_useful_tgt_inlined = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_useful_tgt_suggestions = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_useful_tgt_completion = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_useful_tgt_chunking = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_useful_tgt_anywhere = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )

        # Verdict on interactive MT questions
	exit_cat_strength_weakness = models.TextField()
	exit_itm_strength_weakness = models.TextField()
	exit_itm_missing_aid = models.TextField()
	exit_prefer_itm = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )
	exit_got_better_at_itm = models.PositiveSmallIntegerField( choices = choices.LIKERT_CHOICES, default = None )

        # Any other comments?
	exit_comments = models.TextField()

        def __unicode__(self):
            return self.user.username

ptm/tm/tmapp/templates/index.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
 -- {{ page_title }}
{% endblock %}

{% block user_static %}

{% load compressed %}
{% compressed_css 'tmapp_css' %}

{% endblock %}

{% block header %}
Stanford Translation Study
{% endblock%}

{% block content %}

{% if not status.demographic_form_done %}
<p>Thank you for helping us with this experiment! We are a group of researchers in the <a href="http://cs.stanford.edu/" target="_blank">Computer Science Department at Stanford University</a> working on translation interfaces. Our goal is to how study how translators, like you, use machine-assisted translation systems.</p>

<p><b>Privacy</b>: During the study, we will record your responses (i.e., translations), keystrokes, mouse actions, and browser settings. We will also ask you to fill out two surveys on your demographic information and about your experience with this study. We will not collect any other personal information.</p>

<p><b>Participation</b>: Your participation in this experiment is voluntary. You may stop at any time without any penalty. However, you will only be paid for a completed study. Full payment is contingent on finishing the translation tasks in continuous sessions.</p>

<p>If you have any questions or feedback, please contact <a href="mailto:spenceg@stanford.edu">Spence Green</a>.</p>

<p>By clicking below, you understand that your participation in this study is voluntary, and agree to the collection of your survey and study data.</p>

<div>
<form action="/tm/demographic">
    <input type="submit" value="I Agree">
</form>
</div>

{% else %}

{% if status.show_break %}

<p><b>Take an untimed break.</b>

{% if status.break_type == "ui_break" %}
 When you resume, you will see a <b>new CAT interface</b>.</p>

{% elif status.break_type == "domain_break" %}
 When you resume, you will see a <b>new genre of source text</b>.</p>

{% endif %}
{% endif %}

{% if status.demographic_form_done and not status.training_done %}
<p>Click 'Training' to get started.</p>

{% endif %}

{% if status.training_done and not status.translate_done %}
<p><b>Next translation module</b>: {{ status.ui_mode }} interface for {{ status.src_domain }} text. Click 'Translate' to start.</p>

{% endif %}

<h3> Experiment Steps </h3>
<table id="table-main-steps">
  <tr>
    <td class="left-col"><a href="/tm/training">Training</a></td>
    <td class="right-col"><span {% if status.training_done %} class="step-complete">Complete {% else %} class="step-incomplete">Incomplete {% endif %}</span></td>
  </tr>
  {% if status.training_done %}
  <tr>
    <td class="left-col"><a href="/tm/translate">Translate</a></td>
    <td class="right-col"><span {% if status.translate_done %} class="step-complete">Complete {% else %} class="step-incomplete">Incomplete {% endif %}</span></td>
  </tr>
  {% endif %}
  {% if status.training_done and status.translate_done %}
  <tr>
    <td class="left-col"><a href="/tm/exit">Exit Questionnaire</a></td>
    <td class="right-col"><span {% if status.exit_form_done %} class="step-complete">Complete {% else %} class="step-incomplete">Incomplete {% endif %}</span></td>
  </tr>
  {% endif %}
</table>

<div style="margin-top:2em">
<form action="/bye/">
    <input type="submit" value="Logout">
</form>
</div>

{% endif %}

{% endblock %}

ptm/tm/tmapp/templates/playback.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
 -- {{ page_title }}
{% endblock %}

{% block user_static %}

{% load compressed %}
{% compressed_css 'tmapp_css' %}

{% endblock %}

{% block header %}
Stanford Translation Study
{% endblock%}

{% block content %}

<ul>
{% for session in session_list %}
    <li><a href="/tm/playback/{{ session.id }}" target="_blank">{{ session.user.username }} {{ session.src_document.url }}</a> {{ session.interface }} {{ session.tgt_language.code }}</li>
{% endfor %}
</ul>

{% endblock %}

ptm/tm/tmapp/templates/survey.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
 -- {{ page_name }}
{% endblock %}

{% block user_static %}
{% load compressed %}
{% compressed_css 'tmapp_css' %}
{% endblock %}

{% block header %}
{{ form_title }}
{% endblock%}

{% block content %}
<div id="form-instructions">
{{ form_instructions }}
</div>

<div id="form-wrapper">
<form action="{{ form_action }}" method="post" name="form-survey" id="form-survey">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" name="form-submit" id="form-submit" />
</form>
</div>
{% endblock %}

ptm/tm/tmapp/templates/training.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}
 -- {{ page_name }}
{% endblock %}

{% block user_static %}
{% load compressed %}
{% compressed_css 'tmapp_css' %}
{% compressed_js 'browser_js' %}
{% endblock %}

{% block header %}
{{ page_title }}
{% endblock%}

{% block content %}
<div id="main-content" style="font-size: 1.15em">

{% if step == 0 %}
<p>This training module will test your browser, describe the experiment, and present the translation workbench. You'll have the opportunity to practice by translating some sample documents before the experiment starts.</p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 1 %}
<h3>Browser Check</h3>

<p>We require you to use <a href="http://www.google.com/chrome/" target="_blank">Google Chrome</a> for this experiment. You should:</p>
<ul>
  <li><a href="https://support.google.com/chrome/answer/95416?hl=en" target="_blank">Set both the source and target languages</a> so that Chrome doesn't offer to translate for you.</li>
  <li><a href="https://support.google.com/chrome/answer/95604?hl=en" target="_blank">Disable spell check</a></li>
</ul>

<input type="hidden" name="BrowserLog" id="BrowserLog"></input>
<div id="BrowserReport" style="padding: 0 10px; border: 1px solid #ccc; font-family: PT_Mono, monospace; font-size: 8pt; color: #333">
	<p style='font-weight:bold' id="BrowserUserAgent"></p>
	<!--
	<p style="margin-bottom: 0"><b>Your browser supports:</b></p>
	<p style="margin-top: 0" id="BrowserSupport"></p>
	<p style="margin-bottom: 0"><b>Your browser does not support:</b></p>
	<p style="margin-top: 0" id="BrowserNoSupport"></p>
	<p style="margin-bottom: 0"><b>Your browser passed the following tests:</b></p>
	<p style="margin-top: 0" id="BrowserPass"></p>
	-->
	<p style='font-weight:bold' id="BrowserTestStatus"></p>
</div>

<p>If your browser fails any tests, then first ensure that your browser is the latest version of Chrome. If your browser still fails these checks, then contact the administrators before proceeding. <b>You will not be paid if your browser does not pass prior to starting the experiment.</b></p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 2 %}
<h3>Experiment Goals: Translation Speed &amp; Quality</h3>

<p>During the study, translate the documents as quickly and as accurately as you can.</p>

<p><b>Speed</b>: Once you start working on a document, you <b>may not idle for longer than 3 minutes</b> within a single session. If you pause---meaning an absence of keyboard or mouse input---for 3 continuous minutes, your current set of translations will be automatically submitted. The payment for the equivalent number of words will be deducted from your final pay. Continuing to translate will reset the &ldquo;idle timer,&rdquo; which will be located at the bottom of your browser window.</p>

<p><b>Quality</b>: Once you submit a translated document, you will not have another opportunity to edit it. Make sure that your translation is in good shape before you press the submit button!</p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 3 %}
<h3>Overview of the Experiment</h3>

<p>This website will administer the translation job, which is organized into two modules separated by a break:</p>

<ul>
  <li>Training module (which you're reading now!)</li>
  <li>Translation Module #1 (about 1,500 source words)</li>
  <li>Break (not timed)</li>
  <li>Translation Module #2 (about 1,500 source words)</li>
  <li>Exit Survey</li>
</ul>

<p>Each module features a different CAT interface and consists of documents from three different text genres (software, medical, and newswire). In addition to the break between modules, the site will offer an untimed break each time you switch genres (about every 500 source tokens). Get up, go to the bathroom, get some coffee: whatever you need to stay productive.</p>

<p><b>We require that you complete both translation modules on the same day.</b></p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 4 %}
<h3>Job Description and Requirements</h3>

<p>You will be asked to translate two sets of documents from <b>{{ src_lang }}</b> to <b>{{ tgt_lang }}</b>. You will be presented with paragraphs selected from the documents. You will see the sentences from these paragraphs in the same order in which they appear in the original document.</p>

<p>The text will probably challenge you and may be outside of your area of expertise. Don't worry. We're interested in how accurately you can translate the material relative to other translators. Everyone will be using the same tools.</p>

<p>Please make sure that your {{ tgt_lang }} translation:
<ul>
<li>Is faithful to the original text in both meaning and style</li>
<li>Is grammatical, fluent, and natural-sounding</li>
<li>Does not add or delete information from the original text</li>
<li>Does not contain any spelling errors</li>
</ul>
</p>

<p>When creating your translation, you:
<ul>
<li><b>May use</b> dictionaries, either offline or online (e.g., <a href="http://www.wordreference.com" target="_blank">WordReference</a>).</li>
</ul>

<p>However:
<ul>
<li><b>Do not use</b> any other automatic/machine translation systems (e.g., Google Translate, Trados, etc.)</li>
<li><b>Do not use</b> translation memories or term bases</li>
<li><b>Do not use</b> browser plugins or extensions</li>
</ul>

<p>We will check the translations you submit against those produced by various machine translation systems. We're trying to understand how our specific CAT system works, so please help us by not using other machine assistance.</p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 5 %}
<h3>Description of the CAT Modes</h3>

<p>This experiment tests the difference between two different CAT modes: post-edit and interactive. The modes have similar interfaces that differ only in terms of the type of assistance offered. You will be presented with {{ src_lang }} documents in a sequence. The interface will contain textboxes to enter {{ tgt_lang }} translations. Please translate as quickly and as accurately as you can.</p>

<p>You might notice that both interfaces lack standard aids such as translation memories and spell checking. That's because this experiment focuses on testing new aids, and we're trying to isolate the contributions---if any---of those aids.</p>

<p>Both interfaces adhere to the following {{ tgt_lang }} target text convention:
<ul>
  <li><span style="color:#000">Black text</span> : belongs to human translator, never modified by machine.</li>
  <li><span style="color:#999">Gray text</span> : belongs to machine, never modified by human translator. In the post-edit mode, the gray text immediately becomes black, indicating human ownership. In the interactive mode, the human can accept parts of the gray text, but cannot edit or manipulate it.</li>
</ul>
</p>

<h3>Post-editing Interface</h3>

<p>This is a standard post-editing scenario. Each textbox will be pre-populated with a suggested {{ tgt_lang }} translation in black. You may accept, edit, or delete the suggested translation.</p>

<h3>Interactive Interface</h3>

<p>Each textbox will now be populated with gray text. You can accept the gray text adjacent to your cursor by pressing the <b>Tab</b> key. Accepted text turns black. You may also type text as usual, and edit any black text. Think of it this way: to the left of your cursor is a standard text box, and to the right is a static area that indicates the machine's best suggestion. A drop-down will sometimes show several translation options, and the <b>Tab</b> key always selects the top option. You can filter the drop-down by typing, or navigate it with the arrow keys. The machine suggestion will update in real-time based on the black text that you've accepted. You can select all of the gray text at any time by typing <b>Control+Enter</b>.</p>

<p>The interface is designed to be operated from the keyboard. The various menus are clickable as you would expect, but with some practice we expect that you won't need to lift your hands from the keyboard except to navigate between source sentences.</p>

<p>The interactive interface includes four types of aides:
  <ul>
  <li>Term lookup : implemented as hover over source text. You can click on the term options to accept them.</li>
  <li>Full MT : implemented as gray text.</li>
  <li>In-context translation options : implemented as drop-down and gray text updates while editing.</li>
  <li>Source coverage: implemented as highlighting of source tokens that have already been translated.</li>
  </ul>
</p>

<h3>IMPORTANT: Submitting Translations</h3>
<p>Only black text will be submitted when you press Submit. In interactive mode, if you want to submit a full suggestion, then you need to Tab through it. If there is extra gray text at the end of your translation, don't worry. It won't be submitted. THE GRAY TEXT SIMPLY REFLECTS THE MACHINE'S BEST SUGGESTION.</p>

<div>
<form action="/tm/training/{{ step }}/">
    <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% elif step == 6 %}
<p>Please watch this tutorial, which narrates the features of the CAT interfaces. We recommend that you watch it in full-screen mode to view the text clearly.</p>

<iframe width="640" height="360" src="//www.youtube.com/embed/gEO4o0jSFkQ?rel=0&vq=hd720" frameborder="0" allowfullscreen></iframe>

<h3>IMPORTANT: Using the Interactive Interface</h3>
<p>Interactive translation is a new tool, and we strongly encourage you to consider using it in a new way. We recognize that some translators &ldquo;read through&rdquo; a source text before working. This is called <b>global planning</b>. In the interactive mode, we encourage you to try <b>local planning</b> instead. Read a source phrase or two, and then dive into translation. The machine will revise it's suggestion as you work. Our goal is to improve human translator productivity, and we want to see if you can find a way to use the tool to increase throughput and/or quality. Reducing global planning might be one way to increase productivity.</p>

<h3>Practicing with the Interfaces</h3>
<p>When you press the button below, the translator workbench will open for practice. The workbench will alternate between the post-edit and interactive modes. Take your time, especially with the interactive interface. You don't need to translate all of the sentences or documents---feel free to skip some of them---as they are for practice only. We expect you to develop some proficiency with the interfaces prior to starting the experiment.</p>

<p>We will add an additional $10 to your payment for watching the video and practicing with the workbench.</p>

<p>When you feel proficient, please click the button at the bottom of the workbench interface to return to the homepage. Then you can start the actual translation experiment.</p>

<div>
<form action="{{ ui_link }}">
  <input type="submit" value="{{ form_button_text }}">
</form>
</div>

{% endif %}

</div>

{% endblock %}

ptm/tm/tmapp/templates/translate.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Translation User Interface</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	{% load compressed %}
	{% compressed_css 'ui_css' %}
	{% compressed_js 'ui_js' %}
	<script type="text/javascript">
		$(document).ready( function() {
			ptm = new PTM({
				"postEditMode" : {{ conf.is_postedit }},
				"docURL" : "{{ conf.src_document_url }}",
				"sourceLang" : "{{ conf.src_language }}",
				"targetLang" : "{{ conf.tgt_language }}",
				"maxIdleTime" : "{{ idle_time }}"
			});
			ptm.load();
		});
		var prepareSubmission = function() {
			d3.select(".UPLOADING").transition().style("visibility", "visible");
			var userResponses = ptm.getUserResponses();
			var interactionLog = ptm.getInteractionLog();
			d3.select("#id_text").node().value = JSON.stringify(userResponses);
			d3.select("#id_log").node().value = JSON.stringify(interactionLog);
			return true;
		};
	</script>
</head>
<body style="padding: 0; margin: 0; background: #eee;">
<div class="UPLOADING" style="position: fixed; display: inline-block; width: 100%; height: 100%; top: 0; left: 0; z-index: 95000; background: rgba(255,255,255,0.9); text-align: center; font-family: PT_Serif, serif; color: #333; line-height: 2em; visibility: hidden">
	<div style="font-size: 24pt; color: #000; margin: 200px 0 50px 0">Please Wait.</div>
	<div>We are uploading your responses and mouse/keyboard activities to the server.</div>
	<div>This page will refresh itself when the upload finishes.</div>
	<div>Do not close your browser.</div>
</div>
<div class="PAGE" style="margin: 20px 20px 200px 20px">
  <div id="PTM"></div>
  <div id="form-wrapper" style="margin: 30px 0px">
    <form action="{{ form_action }}" method="post" name="form-tgt-input" id="form-tgt-input" onsubmit="return prepareSubmission()">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="{{ form_button_text }}" name="form-tgt-submit" id="form-tgt-submit" />
    </form>
    {% if training %}
    <form action="/tm/">
      <input type="submit" value="Quit training. I'm ready to start the experiment">
    </form>
    {% endif %}
  </div>
</div>
<div class="ExperimentUI">Experiment will end in <span class="ExperimentTimeRemaining"></span> without continued translations.</div>
</body>
</html>

ptm/tm/tmapp/templates/translate_demo.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Translation User Interface</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	{% load compressed %}
	{% compressed_css 'ui_css' %}
	{% compressed_js 'ui_js' %}
	<script type="text/javascript">
		$(document).ready( function() {
			ptm = new PTM({
				"postEditMode" : false,
				"docURL" : "{{ conf.src_document_url }}",
				"sourceLang" : "{{ conf.src_language }}",
				"targetLang" : "{{ conf.tgt_language }}",
				"maxIdleTime" : "99999"
			});
			ptm.load();
		});
	</script>
</head>
<body style="padding: 0; margin: 0; background: #eee;">
<div class="PAGE" style="margin: 20px 20px 200px 20px">
  <div id="PTM"></div>
</div>
</body>
</html>